epochs: 30
resume: None
learning_rate: 0.0001
weight_decay: 10e-6
inference_device: "cuda"
train:
  s: 1
  batch_size: 8
  num_workers: 10
  valid_size: 0.2
  train_path: "/mnt/promedius_dataset/sobuzang/2021_dataset/data/srpark/new/train"
test:
  batch_size: 8
  num_workers: 8
  test_path: "/mnt/promedius_dataset/sobuzang/2021_dataset/data/srpark/new/test"
model:
  model_arch: "resnet" #"mobilenet"
  sub_model: "resnet34" #"mobilenet_v2"
  classes: 4
  pretrain: True